project_id = "mihkqpovzubwcvurfrbb"

[functions.toast-auth]
verify_jwt = false

[functions.toast-get-data]
verify_jwt = false

[functions.toast-reporting]
verify_jwt = false

[functions.chat-shyloh]
verify_jwt = false

[functions.process-mentions]
verify_jwt = false

[functions.claim-restaurant]
verify_jwt = true